## Bài tập 2 - Thư viện thao tác với cấu trúc Tensor:
Thực ra thư viện NumPy là thư viện nền tảng,
dựa trên nó có nhiều thư viện được phát triển chuyên biệt. Để thao tác với cấu trúc Tensor có 2
thư viện rất nổi tiếng, gồm:
- TensorFlow
- PyTorch

Em xin phép chọn thư viên PyTorch để tương tác với Tensor

Import thư viện Pytorch:

In [20]:
import torch

Tạo hàm show kết quả ra màn hình:

In [13]:
def show_tensor(tensor):
  print("Tensor: \n", tensor)
  print("Tensor hạng: ", tensor.ndim)
  print("Kích thước của tensor: ", tensor.shape)

Tạo tensor hạng 1:

In [3]:
data = [1,2,3]
tensor_1 = torch.tensor(data)

In [14]:
show_tensor(tensor_1)

Tensor: 
 tensor([1, 2, 3])
Tensor hạng:  1
Kích thước của tensor:  torch.Size([3])


Tạo tensor hạng 2:

In [11]:
tensor_2 = torch.rand((2,3))

In [15]:
show_tensor(tensor_2)

Tensor: 
 tensor([[0.8909, 0.9955, 0.2764],
        [0.6416, 0.3572, 0.3295]])
Tensor hạng:  2
Kích thước của tensor:  torch.Size([2, 3])


Tạo tensor hạng 3:

In [10]:
tensor_3 = torch.rand((2,3,4))

In [16]:
show_tensor(tensor_3)

Tensor: 
 tensor([[[0.4250, 0.7872, 0.6781, 0.5723],
         [0.8202, 0.4789, 0.0333, 0.6512],
         [0.7411, 0.5055, 0.8860, 0.1112]],

        [[0.5783, 0.8172, 0.4336, 0.6522],
         [0.2411, 0.3999, 0.7935, 0.5655],
         [0.7655, 0.9769, 0.2904, 0.4819]]])
Tensor hạng:  3
Kích thước của tensor:  torch.Size([2, 3, 4])


Tạo tensor hạng 4:

In [18]:
tensor_4 = torch.rand((2,3,4,5))

In [19]:
show_tensor(tensor_4)

Tensor: 
 tensor([[[[0.1680, 0.6979, 0.6929, 0.0323, 0.1351],
          [0.2405, 0.4225, 0.6683, 0.0782, 0.3173],
          [0.2000, 0.1489, 0.4641, 0.1543, 0.9865],
          [0.6311, 0.4681, 0.8141, 0.8568, 0.5837]],

         [[0.0320, 0.2956, 0.6417, 0.6786, 0.1294],
          [0.9516, 0.3300, 0.3057, 0.1528, 0.4137],
          [0.6611, 0.1571, 0.8333, 0.8390, 0.4643],
          [0.0887, 0.8253, 0.5157, 0.4595, 0.1023]],

         [[0.4385, 0.5770, 0.3969, 0.6986, 0.0272],
          [0.2165, 0.6267, 0.8417, 0.1401, 0.4889],
          [0.6292, 0.0327, 0.2464, 0.0457, 0.7826],
          [0.5562, 0.7420, 0.1560, 0.9903, 0.2970]]],


        [[[0.8538, 0.7262, 0.3417, 0.5373, 0.6150],
          [0.5776, 0.8516, 0.3480, 0.9801, 0.6833],
          [0.6158, 0.3430, 0.2290, 0.4607, 0.7587],
          [0.1283, 0.1758, 0.7242, 0.3738, 0.8496]],

         [[0.1492, 0.8751, 0.5601, 0.0515, 0.1842],
          [0.8506, 0.1876, 0.8736, 0.1713, 0.0432],
          [0.2000, 0.5889, 0.6384, 0.4558, 0