**Tự học Numpy**

---




1. Numpy array và các thuộc tính của nó: 

In [ ]:
#Import thư viện Numpy 
import numpy as np

In [ ]:
my_arr = np.array([[1,2,3],
                  [4,5,6]])
my_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Số dòng, số cột của mảng
my_arr.shape

(2, 3)

In [ ]:
# Số chiều của mảng
my_arr.ndim

2

In [ ]:
# Kiểu dữ liệu phần từ của mảng
my_arr.dtype

dtype('int64')

In [ ]:
# Số phần từ của mảng
my_arr.size

6

2. Tạo Numpy array với built-in function

zeros()

In [ ]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

ones()

In [ ]:
np.ones([4,5], dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

arange()

In [ ]:
np.arange(0, 20, 2, dtype = int)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

full()

In [ ]:
np.full([4,3], 100, dtype = int)

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

linspace()

In [ ]:
# Chia ra trong khoảng từ 0 đến 10, 20 khoảng :))
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

3. random

random.random()

In [ ]:
# random.seed(0) giúp random.random không in ra số ngẫu nhiên thay đổi 
# mỗi lần chúng ta chạy lại
np.random.seed(0)
np.random.random((4,5))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ],
       [0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152],
       [0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606],
       [0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215]])

random.rand()

In [ ]:
# Khác với random.random(), random.rand() nhận đối số là 
# chiều của nó trực tiếp ko cần phải thông qua shape
# Tức là có ngoặc tròn, ngoặc vuông j cả
np.random.rand(4,5)

array([[0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443],
       [0.63992102, 0.14335329, 0.94466892, 0.52184832, 0.41466194],
       [0.26455561, 0.77423369, 0.45615033, 0.56843395, 0.0187898 ],
       [0.6176355 , 0.61209572, 0.616934  , 0.94374808, 0.6818203 ]])

random.normal()

In [ ]:
# Đối số lần lượt là:
# Mean: giá trị trung bình
# Standard Deviation: độ lệch chuẩn 
np.random.normal(5, 2, (4,5))

array([[3.2244285 , 1.03840706, 4.3041757 , 5.31269794, 7.46058136],
       [7.4047597 , 4.22534637, 4.3953945 , 2.90289407, 2.15996413],
       [1.58745962, 8.90155079, 3.98069564, 4.1238514 , 2.49440928],
       [6.55498071, 1.7722043 , 4.57451944, 3.20906688, 5.773805  ]])

random.randint()

In [ ]:
# Từ cái tên chúng ta cũng biết được là random số nguyên
np.random.randint(0,10, [2,3])

array([[2, 4, 2],
       [0, 3, 2]])

4. Array indexing and slicing

In [ ]:
my_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
my_arr[:,:2]

array([[1, 2],
       [4, 5]])

5. Reshape of arrays and transpose

Reshape:

In [ ]:
a = np.arange(0,9,1)
a.shape
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a.reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
b = np.array([1,2,3,4,5])
# Do đó có 5 dòng thì b là một vector cột
b.shape

(5,)

In [ ]:
b = b.reshape(1,5)
b.shape
# Lúc này b trở thành một vector dòng

(1, 5)

Transpose:

In [ ]:
b.T
# Nôm na là ma trận chuyển vị :))

array([[1],
       [2],
       [3],
       [4],
       [5]])

6. Array concatenation and splitting

Array concatenation:

In [ ]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.concatenate((x,y))

array([1, 2, 3, 4, 5, 6])

In [ ]:
a = np.array([[1,2,3],
             [4,5,6]])
b = np.array([[1,2,3],
             [4,5,6]])

In [ ]:
# Nối theo row
np.concatenate((a,b)) # axis = 0 mặc định

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Nối theo column
np.concatenate((a,b), axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [ ]:
# Vertical stack
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Horizontal stack
np.hstack((a,b))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

Splitting:

In [ ]:
x = np.array([1,2,3,4,5,6,7,8,9])

In [ ]:
x1, x2, x3 = np.split(x, [3,5])

In [ ]:
x1

array([1, 2, 3])

In [ ]:
x2

array([4, 5])

In [ ]:
x3

array([6, 7, 8, 9])

7. Broadcasting và vectorise operations

In [ ]:
a = np.arange(3)
a

array([0, 1, 2])

In [ ]:
a + 5 # Broadcasting

array([5, 6, 7])

In [ ]:
b = np.ones((3,3), dtype = int)
b

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
a + b

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

8. Manipulating và Comparing Array

Aggregation

In [ ]:
my_list = [1,2,3,4]

In [ ]:
arr = np.array(my_list)
arr

array([1, 2, 3, 4])

In [ ]:
sum(arr) # Python built-in function

10

Numpy sum:

In [ ]:
np.sum(arr) # Tính toán nhanh hơn python bulit-in function

10

Numpy mean:

In [ ]:
np.mean(arr)

2.5

In [ ]:
np.max(arr)
np.min(arr)

1

Standard Deviation( Độ lệch chuẩn):

In [ ]:
np.std(arr)

1.118033988749895

Variance(Phương sai):

In [ ]:
np.var(arr)

1.25

9. Sorting Array (Được xây dựng dựa trên thuật toán quick sort)




In [ ]:
x = np.array([2,3,4,8,3,5])
np.sort(x)

array([2, 3, 3, 4, 5, 8])

In [ ]:
np.argsort(x)
# sắp xếp, In ra cái index ban đầu của các phân tử trước khi sắp xếp

array([0, 1, 4, 2, 5, 3])

Sort theo cột và dòng:

In [ ]:
np.random.seed(42) # số 42 giống như số đồng bộ :))
x = np.random.randint(0,10,(3,4))

In [ ]:
x

array([[6, 3, 7, 4],
       [6, 9, 2, 6],
       [7, 4, 3, 7]])

Sắp xếp theo cột:

In [ ]:
np.sort(x, axis = 0)

array([[6, 3, 2, 4],
       [6, 4, 3, 6],
       [7, 9, 7, 7]])

Sắp xếp theo hàng:

In [ ]:
np.sort(x, axis = 1)

array([[3, 4, 6, 7],
       [2, 6, 6, 9],
       [3, 4, 7, 7]])

10. Đại số tuyến tính

In [ ]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [ ]:
B = np.array([[6,5],
              [4,3],
              [2,1]])

Nhân hai ma trận (tích vô hướng):

In [ ]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [ ]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])